language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: nVjw2LlPTMjqW0MVIJOXm6JafmhN71NN3CxgprqZ8kF97ApyaqvVPZhCuU6nrwqDu+rvKsxJdytFY8n4b3DrbxPbXJJDS6bjLjRdTYSgOJbFiLzuWBZkKRihpzhcg7oKG9RwPBq0EiM1CugNN493Ld0hAVYEuPWz/WSWxe15DXbtlz92kSZSHSRDD0xO82viDFU/v7LucAlMEcitANvipNSRzBoquHfqpZjvk6XRBnQ63bvzHdYGR7skBk2h2bhpmWmBKNF31lfwFl2PjVtmYiWJWr8vxkD1LnP/H94pVe51LPYBoRu5vkDbJXtxe0XX/sdWPXhJrSIR9igS7FN148huZZVgrm1oIzjR5KAMGZabU7XPw9cM8w0tqicUTWfqqYXR69i5A1Gliuh/AKGi58vwcC+6BmyBRMhbPsc6l05ajt1sY/lCHGwgnwf1/IWVRWA7Wo+OeAtnyXqInMjWCR6a9BXhyRQDsuF3fnggQKbfGBAoMbaX2DaAXld6R96RSmI3jqqTNJIL5KwbgYrKxmCSH14v6rBI95ltDu9kUNEgTPENoYhZ0uC1oxnVzcAya8K0Efr4ngIH8OWt2HNBmyb3NicHD3czAA4MxXYp3wGs2L2qB1+bSjTIv00q4ethq8DPAK/byrzqFrmmGxqdimdg24AT9VNQ7gZ3PCVh2EU=
  app: freshbudgets-api
  skip_cleanup: true
